INSERT INTO [dbo].[Customer]  ([Client],[Contact],[Email],[PhoneNo],[Active],[ContactRole],[ServiceDescription],[PTSPOC])VALUES('MURPHY EXPLORATION','Ken Hampshire',null,'(281) 675-9330',1,null,'All Services',12)
INSERT INTO [dbo].[Customer]  ([Client],[Contact],[Email],[PhoneNo],[Active],[ContactRole],[ServiceDescription],[PTSPOC])VALUES('APACHE CORP','Eloisa Vela',null,'(713) 296-6000',1,null,'All Services',12)
INSERT INTO [dbo].[Customer]  ([Client],[Contact],[Email],[PhoneNo],[Active],[ContactRole],[ServiceDescription],[PTSPOC])VALUES('APACHE DEEPWATER','James Parr',null,'(713) 296-6000',1,null,'All Services',11)
INSERT INTO [dbo].[Customer]  ([Client],[Contact],[Email],[PhoneNo],[Active],[ContactRole],[ServiceDescription],[PTSPOC])VALUES('BP E&P 2016','Carla Guillen',null,'(281) 528-3518',1,null,'WELL TESTING',12)
INSERT INTO [dbo].[Customer]  ([Client],[Contact],[Email],[PhoneNo],[Active],[ContactRole],[ServiceDescription],[PTSPOC])VALUES('FREEPORT McMoran','Deedra Senegal',null,'(713) 579-6933',1,null,'All Services',11)
INSERT INTO [dbo].[Customer]  ([Client],[Contact],[Email],[PhoneNo],[Active],[ContactRole],[ServiceDescription],[PTSPOC])VALUES('SHERIDAN','Daniel Norman',null,'(713) 548-1000',1,null,'All Services',12)
INSERT INTO [dbo].[Customer]  ([Client],[Contact],[Email],[PhoneNo],[Active],[ContactRole],[ServiceDescription],[PTSPOC])VALUES('STONE ENERGY','Heather Whitney ',null,'(281) 872-1999',1,null,'All Services',12)
INSERT INTO [dbo].[Customer]  ([Client],[Contact],[Email],[PhoneNo],[Active],[ContactRole],[ServiceDescription],[PTSPOC])VALUES('LLOG EXPLORATION','Kemberlia Ducote',null,'(985) 801-4300',1,null,'All Services',12)
INSERT INTO [dbo].[Customer]  ([Client],[Contact],[Email],[PhoneNo],[Active],[ContactRole],[ServiceDescription],[PTSPOC])VALUES('TALOS ENERGY','Loni Powell',null,'(713) 328-3036',1,null,'All Services',12)
INSERT INTO [dbo].[Customer]  ([Client],[Contact],[Email],[PhoneNo],[Active],[ContactRole],[ServiceDescription],[PTSPOC])VALUES('GREENE''s ENERGY','Vanessa Flores',null,'(281) 598-6874',1,null,'All Services',12)
INSERT INTO [dbo].[Customer]  ([Client],[Contact],[Email],[PhoneNo],[Active],[ContactRole],[ServiceDescription],[PTSPOC])VALUES('BLUE FIN SERVICES','Bryan Benoit',null,'(337) 365-6677',1,null,'All Services',12)
INSERT INTO [dbo].[Customer]  ([Client],[Contact],[Email],[PhoneNo],[Active],[ContactRole],[ServiceDescription],[PTSPOC])VALUES('BLACKBRUSH OIL & GAS','Eric Friedrichs',null,'(210) 495-5577',1,null,'All Services',12)
INSERT INTO [dbo].[Customer]  ([Client],[Contact],[Email],[PhoneNo],[Active],[ContactRole],[ServiceDescription],[PTSPOC])VALUES('SAMSON RESOURCES','Cindy Rose',null,'(918) 591-1049',1,null,'All Services',12)
INSERT INTO [dbo].[Customer]  ([Client],[Contact],[Email],[PhoneNo],[Active],[ContactRole],[ServiceDescription],[PTSPOC])VALUES('XOG RESOURCES','Joel Gonzalez',null,'(281) 251-4895',1,null,'All Services',12)
INSERT INTO [dbo].[Customer]  ([Client],[Contact],[Email],[PhoneNo],[Active],[ContactRole],[ServiceDescription],[PTSPOC])VALUES('COOK INLET ENERGY','Conrad Perry',null,'(907)433-3816',1,null,'INSPECTION/PIPELINE',12)
INSERT INTO [dbo].[Customer]  ([Client],[Contact],[Email],[PhoneNo],[Active],[ContactRole],[ServiceDescription],[PTSPOC])VALUES('CONOCOPHILIPS ALASKA','Vey A Sasis',null,'(907)265-6102',1,null,'WELL TESTING',12)
INSERT INTO [dbo].[Customer]  ([Client],[Contact],[Email],[PhoneNo],[Active],[ContactRole],[ServiceDescription],[PTSPOC])VALUES('BP ALASKA',null,null,null,1,null,'All Services',12)
INSERT INTO [dbo].[Customer]  ([Client],[Contact],[Email],[PhoneNo],[Active],[ContactRole],[ServiceDescription],[PTSPOC])VALUES('HILCORP ALASKA','Kendra Gousman',null,'(713)757-7116',1,null,'WELL TESTING/SUBSEA',12)
INSERT INTO [dbo].[Customer]  ([Client],[Contact],[Email],[PhoneNo],[Active],[ContactRole],[ServiceDescription],[PTSPOC])VALUES('HWCG','David Coatney',null,'(713)341-5000',1,null,'HWCG - UTILIZATION',12)
INSERT INTO [dbo].[Customer]  ([Client],[Contact],[Email],[PhoneNo],[Active],[ContactRole],[ServiceDescription],[PTSPOC])VALUES('ENVEN ENERGY','David Dunwood',null,'(713)335-7003',1,null,'HWCG - UTILIZATION',13)
INSERT INTO [dbo].[Customer]  ([Client],[Contact],[Email],[PhoneNo],[Active],[ContactRole],[ServiceDescription],[PTSPOC])VALUES('ACCUMULATE ENERGY','Erik Opstad',null,'(907)244-=5210',1,null,'All Services',null)
INSERT INTO [dbo].[Customer]  ([Client],[Contact],[Email],[PhoneNo],[Active],[ContactRole],[ServiceDescription],[PTSPOC])VALUES('NOBLE ENERGY','Elizabeth Marquez',null,'(281)872-2558',1,null,'HWCG - UTILIZATION',null)
INSERT INTO [dbo].[Customer]  ([Client],[Contact],[Email],[PhoneNo],[Active],[ContactRole],[ServiceDescription],[PTSPOC])VALUES('SOUTHWESTERN ENERGY','Deanna Gamble',null,'(501)548-6864',1,null,'All Services',null)
INSERT INTO [dbo].[Customer]  ([Client],[Contact],[Email],[PhoneNo],[Active],[ContactRole],[ServiceDescription],[PTSPOC])VALUES('FREPORT McMoRan','Michele Qquendo',null,'(713)579-6000',1,null,'HWCG - UTILIZATION',null)
INSERT INTO [dbo].[Customer]  ([Client],[Contact],[Email],[PhoneNo],[Active],[ContactRole],[ServiceDescription],[PTSPOC])VALUES('LINC ENERGY','Scott Broussard',null,'(713)580-6600',1,null,'All Services',null)
INSERT INTO [dbo].[Customer]  ([Client],[Contact],[Email],[PhoneNo],[Active],[ContactRole],[ServiceDescription],[PTSPOC])VALUES('MURPHY','Ken Hampshire',null,'(281)675-9330',1,null,'HWCG - UTILIZATION',11)
INSERT INTO [dbo].[Customer]  ([Client],[Contact],[Email],[PhoneNo],[Active],[ContactRole],[ServiceDescription],[PTSPOC])VALUES('MACK ENERGY','John Duty',null,'(575)748-1288',1,null,'All Services',13)
INSERT INTO [dbo].[Customer]  ([Client],[Contact],[Email],[PhoneNo],[Active],[ContactRole],[ServiceDescription],[PTSPOC])VALUES('BLUECREST ALASKA','Bruni Warrick',null,'(907)754-9550',1,null,'All Services',13)
INSERT INTO [dbo].[Customer]  ([Client],[Contact],[Email],[PhoneNo],[Active],[ContactRole],[ServiceDescription],[PTSPOC])VALUES('BRIGHAM OIL & GAS','Michelle Yalung',null,'(512)427-3300',1,null,'All Services',11)
INSERT INTO [dbo].[Customer]  ([Client],[Contact],[Email],[PhoneNo],[Active],[ContactRole],[ServiceDescription],[PTSPOC])VALUES('GREAT BEAR PETROLEUM','Karen Duncan',null,'(907)868-8070',1,null,'All Services',12)
INSERT INTO [dbo].[Customer]  ([Client],[Contact],[Email],[PhoneNo],[Active],[ContactRole],[ServiceDescription],[PTSPOC])VALUES('XTO ENERGY','Scott Steindorf',null,'(907)776-2511',1,null,'All Services',13)
INSERT INTO [dbo].[Customer]  ([Client],[Contact],[Email],[PhoneNo],[Active],[ContactRole],[ServiceDescription],[PTSPOC])VALUES('NORDAQ','Robert Narthen',null,'(907)395-0305',1,null,'All Services',12)
INSERT INTO [dbo].[Customer]  ([Client],[Contact],[Email],[PhoneNo],[Active],[ContactRole],[ServiceDescription],[PTSPOC])VALUES('ALTA MESA','Carmen Camacho',null,'(281)530-0991',1,null,'All Services',13)
INSERT INTO [dbo].[Customer]  ([Client],[Contact],[Email],[PhoneNo],[Active],[ContactRole],[ServiceDescription],[PTSPOC])VALUES('CAELUS ENERGY','Rebecca Gitzen',null,'(907)343-2145',1,null,'All Services',12)
INSERT INTO [dbo].[Customer]  ([Client],[Contact],[Email],[PhoneNo],[Active],[ContactRole],[ServiceDescription],[PTSPOC])VALUES('SHULUMBERGER','ROBERT BERGERON',null,'(281)285-8071',1,null,'Attached the list',13)
INSERT INTO [dbo].[Customer]  ([Client],[Contact],[Email],[PhoneNo],[Active],[ContactRole],[ServiceDescription],[PTSPOC])VALUES('WEATHERFORD','Scott Mettauer',null,'(713) 836-6537',1,null,'All Services',13)
INSERT INTO [dbo].[Customer]  ([Client],[Contact],[Email],[PhoneNo],[Active],[ContactRole],[ServiceDescription],[PTSPOC])VALUES('W&T',null,null,null,1,null,null,13)
INSERT INTO [dbo].[Customer]  ([Client],[Contact],[Email],[PhoneNo],[Active],[ContactRole],[ServiceDescription],[PTSPOC])VALUES('FIELDWOOD',null,null,null,1,null,null,13)
INSERT INTO [dbo].[Customer]  ([Client],[Contact],[Email],[PhoneNo],[Active],[ContactRole],[ServiceDescription],[PTSPOC])VALUES('BHP',null,null,null,1,null,null,13)
INSERT INTO [dbo].[Customer]  ([Client],[Contact],[Email],[PhoneNo],[Active],[ContactRole],[ServiceDescription],[PTSPOC])VALUES('ANADARCO',null,null,null,1,null,null,13)
INSERT INTO [dbo].[Customer]  ([Client],[Contact],[Email],[PhoneNo],[Active],[ContactRole],[ServiceDescription],[PTSPOC])VALUES('ARENE',null,null,null,1,null,null,13)
INSERT INTO [dbo].[Customer]  ([Client],[Contact],[Email],[PhoneNo],[Active],[ContactRole],[ServiceDescription],[PTSPOC])VALUES('OCEANEERING',null,null,null,1,null,null,13)
INSERT INTO [dbo].[Customer]  ([Client],[Contact],[Email],[PhoneNo],[Active],[ContactRole],[ServiceDescription],[PTSPOC])VALUES('COX',null,null,null,1,null,null,13)
INSERT INTO [dbo].[Customer]  ([Client],[Contact],[Email],[PhoneNo],[Active],[ContactRole],[ServiceDescription],[PTSPOC])VALUES('PETROBRAS USA',null,null,null,1,null,null,12)
INSERT INTO [dbo].[Customer]  ([Client],[Contact],[Email],[PhoneNo],[Active],[ContactRole],[ServiceDescription],[PTSPOC])VALUES('EXXON MOBIL',null,null,null,1,null,null,12)
INSERT INTO [dbo].[Customer]  ([Client],[Contact],[Email],[PhoneNo],[Active],[ContactRole],[ServiceDescription],[PTSPOC])VALUES('SHELL','Marcelo Hilario',null,'(21)9161-7255',1,null,'Art. 3',13)
INSERT INTO [dbo].[Customer]  ([Client],[Contact],[Email],[PhoneNo],[Active],[ContactRole],[ServiceDescription],[PTSPOC])VALUES('MODEC','Marco Grassi',null,'(22)2105-1126',1,null,'Art. 3',12)
INSERT INTO [dbo].[Customer]  ([Client],[Contact],[Email],[PhoneNo],[Active],[ContactRole],[ServiceDescription],[PTSPOC])VALUES('BW OFFSHORE',null,null,null,1,null,null,13)
INSERT INTO [dbo].[Customer]  ([Client],[Contact],[Email],[PhoneNo],[Active],[ContactRole],[ServiceDescription],[PTSPOC])VALUES('PETROBRAS BR','Carolina Vaillant',null,'(22)99918-2384',1,null,'Art.2',12)
INSERT INTO [dbo].[Customer]  ([Client],[Contact],[Email],[PhoneNo],[Active],[ContactRole],[ServiceDescription],[PTSPOC])VALUES('BP',null,null,null,1,null,null,13)
INSERT INTO [dbo].[Customer]  ([Client],[Contact],[Email],[PhoneNo],[Active],[ContactRole],[ServiceDescription],[PTSPOC])VALUES('MAERSK',null,null,null,1,null,null,12)
INSERT INTO [dbo].[Customer]  ([Client],[Contact],[Email],[PhoneNo],[Active],[ContactRole],[ServiceDescription],[PTSPOC])VALUES('OGX',null,null,null,1,null,null,13)
INSERT INTO [dbo].[Customer]  ([Client],[Contact],[Email],[PhoneNo],[Active],[ContactRole],[ServiceDescription],[PTSPOC])VALUES('TEEKAY',null,null,null,1,null,null,13)
INSERT INTO [dbo].[Customer]  ([Client],[Contact],[Email],[PhoneNo],[Active],[ContactRole],[ServiceDescription],[PTSPOC])VALUES('PERENCO',null,null,null,1,null,null,13)
INSERT INTO [dbo].[Customer]  ([Client],[Contact],[Email],[PhoneNo],[Active],[ContactRole],[ServiceDescription],[PTSPOC])VALUES('SBM OFFSHORE','Paul Wittle',null,'(21)99279-5568',1,null,'Art. 3',13)
INSERT INTO [dbo].[Customer]  ([Client],[Contact],[Email],[PhoneNo],[Active],[ContactRole],[ServiceDescription],[PTSPOC])VALUES('STATOIL',null,null,null,1,null,null,13)
INSERT INTO [dbo].[Customer]  ([Client],[Contact],[Email],[PhoneNo],[Active],[ContactRole],[ServiceDescription],[PTSPOC])VALUES('SAIPEN',null,null,null,1,null,null,13)
INSERT INTO [dbo].[Customer]  ([Client],[Contact],[Email],[PhoneNo],[Active],[ContactRole],[ServiceDescription],[PTSPOC])VALUES('EXXON','JOHN ZDANSKY',null,'(713)680-5274',0,null,'WELL TESTING',13)
INSERT INTO [dbo].[Customer]  ([Client],[Contact],[Email],[PhoneNo],[Active],[ContactRole],[ServiceDescription],[PTSPOC])VALUES('CHEVRON','STELLA DeROSSO',null,'(713)372-0182',0,null,'LAST SCOPE OF WORK',13)
INSERT INTO [dbo].[Customer]  ([Client],[Contact],[Email],[PhoneNo],[Active],[ContactRole],[ServiceDescription],[PTSPOC])VALUES('KING RANCH','LINDA THOMAS',null,'(713)752-5700',0,null,'All Services',13)
INSERT INTO [dbo].[Customer]  ([Client],[Contact],[Email],[PhoneNo],[Active],[ContactRole],[ServiceDescription],[PTSPOC])VALUES('CHESAPEAK ENERGY',null,null,'(877)245-1427',0,null,'All Services',null)
INSERT INTO [dbo].[Customer]  ([Client],[Contact],[Email],[PhoneNo],[Active],[ContactRole],[ServiceDescription],[PTSPOC])VALUES('BRIGHAM RESOURCES','MICHELLE YALUNG',null,'(512)427-3300',0,null,'All Services',null)
INSERT INTO [dbo].[Customer]  ([Client],[Contact],[Email],[PhoneNo],[Active],[ContactRole],[ServiceDescription],[PTSPOC])VALUES('BJ Services','Sujay Chandrahas',null,null,0,null,null,null)

INSERT INTO [dbo].[Customer]  ([Client],[Contact],[Email],[PhoneNo],[Active],[ContactRole],[ServiceDescription],[PTSPOC])VALUES('MARATHON OIL','Eric Stone',null,'(713) 296-3480',0,null,null,null)
INSERT INTO [dbo].[Customer]  ([Client],[Contact],[Email],[PhoneNo],[Active],[ContactRole],[ServiceDescription],[PTSPOC])VALUES('BENNU OIL & GAS','Denise Brown',null,'(713) 552-5143',0,null,null,null)
INSERT INTO [dbo].[Customer]  ([Client],[Contact],[Email],[PhoneNo],[Active],[ContactRole],[ServiceDescription],[PTSPOC])VALUES('HESS',null,null,null,0,null,null,null)
INSERT INTO [dbo].[Customer]  ([Client],[Contact],[Email],[PhoneNo],[Active],[ContactRole],[ServiceDescription],[PTSPOC])VALUES('DEEP GULF ENERGY','Jeniffer Controlla',null,'(281) 596-0933',0,null,null,null)
INSERT INTO [dbo].[Customer]  ([Client],[Contact],[Email],[PhoneNo],[Active],[ContactRole],[ServiceDescription],[PTSPOC])VALUES('COBALT INT. ENERGY','Procurement Dept.',null,'(713) 579-9134',0,null,null,null)
INSERT INTO [dbo].[Customer]  ([Client],[Contact],[Email],[PhoneNo],[Active],[ContactRole],[ServiceDescription],[PTSPOC])VALUES('ENI US OPERATING','Brian Wiese',null,'(713) 393-6326',0,null,null,null)
INSERT INTO [dbo].[Customer]  ([Client],[Contact],[Email],[PhoneNo],[Active],[ContactRole],[ServiceDescription],[PTSPOC])VALUES('MARUBENI','Katie Gray',null,'(832) 379-6321',0,null,null,null)
INSERT INTO [dbo].[Customer]  ([Client],[Contact],[Email],[PhoneNo],[Active],[ContactRole],[ServiceDescription],[PTSPOC])VALUES('WALTER OIL & GAS','Carmen Fox',null,'(713) 659-1221',0,null,null,null)
INSERT INTO [dbo].[Customer]  ([Client],[Contact],[Email],[PhoneNo],[Active],[ContactRole],[ServiceDescription],[PTSPOC])VALUES('W&T OFFSHORE','Brian Hotard',null,'(504) 210-8164',0,null,null,null)
INSERT INTO [dbo].[Customer]  ([Client],[Contact],[Email],[PhoneNo],[Active],[ContactRole],[ServiceDescription],[PTSPOC])VALUES('REPSOL','M G SMITH',null,'(281)297-1000',0,null,null,null)
INSERT INTO [dbo].[Customer]  ([Client],[Contact],[Email],[PhoneNo],[Active],[ContactRole],[ServiceDescription],[PTSPOC])VALUES('PETRORIO',null,null,null,0,null,null,null)

