
--States
Set IDENTITY_INSERT  [States] ON

INSERT INTO [dbo].[States](Id,[StateName],[Code]) VALUES(1,'Alabama','AL')
INSERT INTO [dbo].[States](Id,[StateName],[Code]) VALUES(2,'Alaska','AK')
INSERT INTO [dbo].[States](Id,[StateName],[Code]) VALUES(3,'Arizona','AZ')
INSERT INTO [dbo].[States](Id,[StateName],[Code]) VALUES(4,'Armed Forces America','AA')
INSERT INTO [dbo].[States](Id,[StateName],[Code]) VALUES(5,'California','CA')
INSERT INTO [dbo].[States](Id,[StateName],[Code]) VALUES(6,'Colorado','CO')
INSERT INTO [dbo].[States](Id,[StateName],[Code]) VALUES(7,'Connecticut','CT')
INSERT INTO [dbo].[States](Id,[StateName],[Code]) VALUES(8,'Delware','DE')
INSERT INTO [dbo].[States](Id,[StateName],[Code]) VALUES(9,'District of Columbia','DC')
INSERT INTO [dbo].[States](Id,[StateName],[Code]) VALUES(10,'Florida','FL')
INSERT INTO [dbo].[States](Id,[StateName],[Code]) VALUES(11,'Georgia','GA')
INSERT INTO [dbo].[States](Id,[StateName],[Code]) VALUES(12,'Hawaii','HI')
INSERT INTO [dbo].[States](Id,[StateName],[Code]) VALUES(13,'Idaho','ID')
INSERT INTO [dbo].[States](Id,[StateName],[Code]) VALUES(14,'Illinois','IL')
INSERT INTO [dbo].[States](Id,[StateName],[Code]) VALUES(15,'Indiana','IN')
INSERT INTO [dbo].[States](Id,[StateName],[Code]) VALUES(16,'Iowa','IA')
INSERT INTO [dbo].[States](Id,[StateName],[Code]) VALUES(17,'Kansas','KS')
INSERT INTO [dbo].[States](Id,[StateName],[Code]) VALUES(18,'Kentucky','KY')
INSERT INTO [dbo].[States](Id,[StateName],[Code]) VALUES(19,'Louisiana','LA')
INSERT INTO [dbo].[States](Id,[StateName],[Code]) VALUES(20,'Maine','ME')
INSERT INTO [dbo].[States](Id,[StateName],[Code]) VALUES(21,'Maryland','MD')
INSERT INTO [dbo].[States](Id,[StateName],[Code]) VALUES(22,'Massachusetts','MA')
INSERT INTO [dbo].[States](Id,[StateName],[Code]) VALUES(23,'Michigan','MI')
INSERT INTO [dbo].[States](Id,[StateName],[Code]) VALUES(24,'Minnesota','MN')
INSERT INTO [dbo].[States](Id,[StateName],[Code]) VALUES(25,'Mississippi','MS')
INSERT INTO [dbo].[States](Id,[StateName],[Code]) VALUES(26,'Missouri','MO')
INSERT INTO [dbo].[States](Id,[StateName],[Code]) VALUES(27,'Montana','MT')
INSERT INTO [dbo].[States](Id,[StateName],[Code]) VALUES(28,'Nebraska','NE')
INSERT INTO [dbo].[States](Id,[StateName],[Code]) VALUES(29,'Nevada','NV')
INSERT INTO [dbo].[States](Id,[StateName],[Code]) VALUES(30,'New Hampshire','NH')
INSERT INTO [dbo].[States](Id,[StateName],[Code]) VALUES(31,'New Jersey','NJ')
INSERT INTO [dbo].[States](Id,[StateName],[Code]) VALUES(32,'New Mexico','NM')
INSERT INTO [dbo].[States](Id,[StateName],[Code]) VALUES(33,'New York','NY')
INSERT INTO [dbo].[States](Id,[StateName],[Code]) VALUES(34,'North Carolina','NC')
INSERT INTO [dbo].[States](Id,[StateName],[Code]) VALUES(35,'North Dakota','ND')
INSERT INTO [dbo].[States](Id,[StateName],[Code]) VALUES(36,'Ohio','OH')
INSERT INTO [dbo].[States](Id,[StateName],[Code]) VALUES(37,'Oklahama','OK')
INSERT INTO [dbo].[States](Id,[StateName],[Code]) VALUES(38,'Oregon','OR')
INSERT INTO [dbo].[States](Id,[StateName],[Code]) VALUES(39,'Pennsylvania','PA')
INSERT INTO [dbo].[States](Id,[StateName],[Code]) VALUES(40,'Rhode Island','RI')
INSERT INTO [dbo].[States](Id,[StateName],[Code]) VALUES(41,'South Carolina','SC')
INSERT INTO [dbo].[States](Id,[StateName],[Code]) VALUES(42,'South Dakota','SD')
INSERT INTO [dbo].[States](Id,[StateName],[Code]) VALUES(43,'Tennessee','TN')
INSERT INTO [dbo].[States](Id,[StateName],[Code]) VALUES(44,'Texas','TX')
INSERT INTO [dbo].[States](Id,[StateName],[Code]) VALUES(45,'Utah','UT')
INSERT INTO [dbo].[States](Id,[StateName],[Code]) VALUES(46,'Vermont','VT')
INSERT INTO [dbo].[States](Id,[StateName],[Code]) VALUES(47,'Virginia','VA')
INSERT INTO [dbo].[States](Id,[StateName],[Code]) VALUES(48,'Washington','WA')
INSERT INTO [dbo].[States](Id,[StateName],[Code]) VALUES(49,'West Virginia','WV')
INSERT INTO [dbo].[States](Id,[StateName],[Code]) VALUES(50,'Wisconsin','WI')
INSERT INTO [dbo].[States](Id,[StateName],[Code]) VALUES(51,'Wyoming','WY')

Set IDENTITY_INSERT  [States] OFF